name: Deploy Midas a IIS - QA

on:
  push:
    branches:
      - qa
 
jobs:
  deploy:
    runs-on: self-hosted
    environment: qa          
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm install

      - name: Compilar
        run: npm run build
        env:
          VITE_JDE_BASE_URL: ${{ secrets.VITE_JDE_BASE_URL }}
          VITE_JDE_TOKEN: ${{ secrets.VITE_JDE_TOKEN }}
          VITE_JDE_ENVIRONMENT: ${{ secrets.VITE_JDE_ENVIRONMENT }}
          VITE_ADMIN_PASSWORD: ${{ secrets.VITE_ADMIN_PASSWORD }}
          VITE_PAOLO_PASSWORD: ${{ secrets.VITE_PAOLO_PASSWORD }}
          VITE_USER_ROLES: ${{ secrets.VITE_USER_ROLES }}
          VITE_DEFAULT_ROLE: ${{ secrets.VITE_DEFAULT_ROLE }}
          VITE_CURRENT_USER_EMAIL: ${{ secrets.VITE_CURRENT_USER_EMAIL }}

      - name: Copiar a IIS - QA
        run: |
          xcopy /E /Y /I dist\* C:\desarrollo\sitios\midas-qa\
          xcopy /E /Y /I public\logos\* C:\desarrollo\sitios\midas-qa\logos\
          copy public\clientes-db.json C:\desarrollo\sitios\midas-qa\clientes-db.json
